name: cute_theme_annotation
description: Annotations for the CuteTheme code-generator.
version: 0.0.2
repository: "https://github.com/isa1vatore/flutter-cute/tree/main/packages/cute_theme_annotation"
homepage: "https://github.com/isa1vatore/flutter-cute/tree/main/packages/cute_theme_annotation"

environment:
  sdk: '>=2.18.0 <3.0.0'