name: cute_theme_annotation
description: A new Flutter package project.
version: 0.0.1
repository: "https://github.com/isa1vatore/flutter-cute/tree/main/packages/cute_theme_annotation"
homepage: "https://github.com/isa1vatore/flutter-cute/tree/main/packages/cute_theme_annotation"

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
