name: cute_theme
description: Code generator for Flutter ThemeExtension.
version: 0.0.2
repository: "https://github.com/isa1vatore/flutter-cute/tree/main/packages/cute_theme"
homepage: "https://github.com/isa1vatore/flutter-cute/tree/main/packages/cute_theme"

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ">=3.0.0 <5.0.0"
  build_config: ^1.1.0
  build: ^2.3.0
  source_gen: ^1.2.2
  source_helper: ^1.3.2

  cute_theme_annotation: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.0