name: coffee_3in1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cute_di_scope:
    path: ../../packages/cute_di_scope
  provider:

  cute_wm:
    path: ../../packages/cute_wm

  cute_theme_annotation:
    path: ../../packages/cute_theme_annotation

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  cute_theme:
    path: ../../packages/cute_theme

  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
