name: coffee_3in1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cute_wm:
    path: ../../packages/cute_wm

  cute_di_scope: ^0.0.1
  cute_theme_annotation: ^0.0.2

  provider:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  cute_theme: ^0.0.2

  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
